# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  blueprincetools:
    image: blueprincetools
    build:
      context: .
      dockerfile: BluePrinceTools.Web/Dockerfile
    ports:
      - 5262:5262
